# Generated by Django 5.2.7 on 2025-12-08 05:58

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk_type', models.CharField(max_length=50)),
                ('area_sqft', models.IntegerField(help_text='Enter area in numeric square feet.', verbose_name='Area (Sq.ft)')),
                ('price_in_rupees', models.IntegerField(help_text='Enter price in total rupees (e.g., 5000000).', verbose_name='Price (in ₹)')),
            ],
            options={
                'ordering': ['bhk_type'],
            },
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('contacted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Enquiry',
                'verbose_name_plural': '3. Project Enquiries',
                'ordering': ['-contacted_on'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('welcome_to_bg', models.ImageField(blank=True, null=True, upload_to='headers/')),
                ('virtual_site_visit_bg', models.ImageField(blank=True, null=True, upload_to='headers/')),
                ('schedule_a_site_visit', models.ImageField(blank=True, null=True, upload_to='headers/')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RERA_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='overviewimage/')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('project_registered', models.CharField(blank=True, max_length=50, null=True)),
                ('government_rera_authorised_advertiser', models.CharField(blank=True, max_length=150, null=True)),
                ('site_address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_us', models.CharField(blank=True, max_length=500, null=True)),
                ('disclaimer', models.CharField(blank=True, max_length=1500, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='rera_docs/')),
            ],
        ),
        migrations.CreateModel(
            name='USP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='web_slider/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=5500, null=True)),
                ('read_more', models.TextField(blank=True, max_length=5500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('discripation', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='utility.projectamenities')),
            ],
        ),
        migrations.CreateModel(
            name='BankOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_offers', to='utility.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupancy_Certificate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
                ('Commencement_Certificate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
                ('construction_status', models.CharField(choices=[('Under Construction', 'Under Construction'), ('New Launch', 'New Launch'), ('Partially Ready To Move', 'Partially Ready To Move'), ('Ready To Move', 'Ready To Move'), ('Deleverd', 'Deleverd')], max_length=25)),
                ('project_name', models.CharField(max_length=250)),
                ('land_parce', models.CharField(blank=True, max_length=50, null=True)),
                ('bhk_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('5 BHK', '5 BHK'), ('6 BHK', '6 BHK'), ('7 BHK', '7 BHK'), ('8 BHK', '8 BHK'), ('9 BHK', '9 BHK'), ('10 BHK', '10 BHK'), ('10+ BHK', '10+ BHK')], max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('possession_month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Select Possession Month', max_length=20, null=True)),
                ('luxurious', models.CharField(blank=True, max_length=50, null=True)),
                ('priceing', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_embed_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='YouTube Video ID')),
                ('featured_property', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('google_map_iframe', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=555, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
            ],
            options={
                'verbose_name_plural': '1. Project',
            },
        ),
    ]
