# Generated by Django 5.2.7 on 2025-12-08 05:58

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('user', '0001_initial'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.developer'),
        ),
        migrations.AddField(
            model_name='project',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.locality'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='possession_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.possessionin'),
        ),
        migrations.AddField(
            model_name='project',
            name='propert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.propertytype'),
        ),
        migrations.AddField(
            model_name='overview',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='projects.project'),
        ),
        migrations.AddField(
            model_name='header',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='projects.project'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='projects.project'),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='bookingoffer',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookingOffer', to='projects.project'),
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_offers', to='projects.project'),
        ),
        migrations.AddField(
            model_name='amenities',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='projects.project'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutus', to='projects.project'),
        ),
        migrations.AddField(
            model_name='rera_info',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rera', to='projects.project'),
        ),
        migrations.AddField(
            model_name='usp',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usps', to='projects.project'),
        ),
        migrations.AddField(
            model_name='webslider',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='projects.project'),
        ),
        migrations.AddField(
            model_name='welcometo',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcomes', to='projects.project'),
        ),
        migrations.AddField(
            model_name='whyinvest',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_invest', to='projects.project'),
        ),
    ]
