# Generated by Django 5.2.7 on 2025-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='unit_plan',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
