# Generated by Django 5.2.7 on 2025-12-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_configuration_parking_configuration_unit_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
