# Generated by Django 5.2.7 on 2025-12-24 10:26

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='bhk_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('6 BHK', '6 BHK'), ('7 BHK', '7 BHK'), ('8 BHK', '8 BHK'), ('9 BHK', '9 BHK'), ('10 BHK', '10 BHK'), ('10+ BHK', '10+ BHK')], max_length=50, null=True),
        ),
    ]
