# Generated by Django 5.2.7 on 2025-12-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_balcony_alter_project_bhk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
