# Generated by Django 5.2.7 on 2025-12-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='master_plan',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
