# Generated by Django 5.2.7 on 2025-12-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_floor_plan_project_master_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivity',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity', to='projects.project'),
        ),
    ]
