# Generated by Django 5.2.7 on 2025-12-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_connectivity_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sold_out',
        ),
        migrations.AddField(
            model_name='configuration',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
