# Generated by Django 5.2.7 on 2025-12-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_balcony_remove_project_sold_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='price_in_rupees',
            field=models.IntegerField(blank=True, help_text='Enter price in total rupees (e.g., 5000000).', null=True, verbose_name='Price (in ₹)'),
        ),
    ]
