# Generated by Django 5.2.7 on 2026-01-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_configuration_price_in_rupees'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_view',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
