# Generated by Django 5.2.7 on 2026-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectcontactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='towers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
