# Generated by Django 5.2.7 on 2026-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_towers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rera_approved',
            field=models.BooleanField(default=False),
        ),
    ]
