# Generated by Django 5.2.7 on 2026-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_rera_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectivity',
            options={'ordering': ['order'], 'verbose_name_plural': 'Connectivity'},
        ),
        migrations.AddField(
            model_name='connectivity',
            name='distance',
            field=models.CharField(blank=True, help_text='Example: 2 Min, 500 M, 3 KM', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-location-dot', help_text='Font Awesome icon class', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='connectivity',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
