# Generated by Django 5.2.7 on 2026-01-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_brochurelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinforesponse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
