# Generated by Django 5.2.7 on 2026-01-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_floorplanrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FloorPlanRequest',
        ),
    ]
