# Generated by Django 5.2.7 on 2026-01-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_delete_floorplanrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinforesponse',
            name='type',
            field=models.CharField(blank=True, choices=[('book_visit', 'Book Visit'), ('get_price', 'Get Price')], max_length=20, null=True),
        ),
    ]
