# Generated by Django 5.2.7 on 2026-01-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0007_alter_additionalinforesponse_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leadgen_id', models.CharField(max_length=100, unique=True)),
                ('form_id', models.CharField(blank=True, max_length=100, null=True)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('configuration', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=120, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
