# Generated by Django 5.2.7 on 2026-05-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectcontactperson'),
        ('response', '0008_metalead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('get_price', 'Get Price'), ('book_visit', 'Book Visit'), ('configuration', 'Configuration'), ('brochure', 'Brochure Download'), ('floor_plan', 'Floor Plan'), ('general', 'General Enquiry')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('configuration', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalInfoResponse',
        ),
        migrations.RemoveField(
            model_name='brochurelead',
            name='project',
        ),
        migrations.DeleteModel(
            name='ConfigurationResponse',
        ),
        migrations.DeleteModel(
            name='BrochureLead',
        ),
    ]
