# Generated by Django 5.2.7 on 2025-12-08 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bhk', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Upcoming', 'Upcoming')], default='Available', max_length=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='properties/main/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='properties/cover/')),
                ('builder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='utility.propertyamenities')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utility.city')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utility.locality')),
                ('possession_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.possessionin')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='projects.project')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utility.propertytype')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
