# Generated by Django 5.2.7 on 2025-12-08 05:58

import ckeditor_uploader.fields
import utility.compress_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_bg', models.ImageField(blank=True, help_text='Background image for the top search banner (optional)', null=True, upload_to='about/backgrounds/')),
                ('home_bg', models.ImageField(blank=True, help_text='Background image for home about section', null=True, upload_to='about/backgrounds/')),
                ('title', models.CharField(help_text="Main heading (e.g., 'About Makaan Hub')", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or tagline', max_length=300, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed About Us content with formatting', null=True)),
                ('image', models.ImageField(blank=True, help_text='Main image for About section', null=True, upload_to='about/')),
                ('who_we_are_title', models.CharField(default='Who We Are', max_length=200)),
                ('who_we_are_subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('who_we_are_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description about company identity', null=True)),
                ('projects_delivered', models.PositiveIntegerField(default=0)),
                ('happy_families', models.PositiveIntegerField(default=0)),
                ('years_of_excellence', models.PositiveIntegerField(default=0)),
                ('awards_recognitions', models.PositiveIntegerField(default=0)),
                ('highlight_icon_color', models.CharField(blank=True, help_text='Optional color for highlight icons (e.g., #0066ff)', max_length=50, null=True)),
                ('our_mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('our_mission', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('our_vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('our_vision', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('looking_to_title', models.CharField(help_text="Title for 'Looking To...' section", max_length=200)),
                ('looking_to_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('looking_to_button_text', models.CharField(default='Contact Us', help_text='Call-to-action button text', max_length=50)),
                ('looking_to_button_link', models.URLField(blank=True, help_text='Button link (e.g., contact page)', null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='SEO keywords separated by commas', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="If disabled, this section won't appear on site")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '2. About Section',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('sub_heading', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_iframe', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Contact Page',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': '7. FAQ Section',
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=100)),
                ('designation', models.CharField(help_text='Position or title (e.g., CEO, Managing Director)', max_length=150)),
                ('image', models.ImageField(help_text='Profile image (recommended size 400x400)', upload_to='about/leadership/')),
                ('bio', models.TextField(blank=True, help_text='Short bio or description about this leader', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Optional LinkedIn profile link', null=True)),
                ('email', models.EmailField(blank=True, help_text='Optional contact email for public display', max_length=254, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance on frontend')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility on frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '3. Leadership Team',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Our_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Our Team',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('search_bg', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('testmonial_bg', models.ImageField(upload_to='logo/')),
                ('header_footer_color', models.CharField(blank=True, max_length=150)),
                ('text_color', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('google_map', models.CharField(blank=True, max_length=1000)),
                ('smtpserver', models.CharField(blank=True, max_length=50)),
                ('smtpemail', models.CharField(blank=True, max_length=50)),
                ('smtppassword', models.CharField(blank=True, max_length=10)),
                ('smtpport', models.CharField(blank=True, max_length=5)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=250, null=True)),
                ('copy_right', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
            ],
            options={
                'verbose_name_plural': '0. Website Settings',
            },
            bases=(utility.compress_mixin.ImageCompressionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='slider/')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '1. Slider Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('rating', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name_plural': '5. Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Why_Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on frontend')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility on frontend')),
            ],
            options={
                'verbose_name_plural': '6. Why Choose Section',
                'ordering': ['order'],
            },
        ),
    ]
