# Generated by Django 5.2.7 on 2025-12-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='rera_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
