# Generated by Django 5.2.7 on 2025-12-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setting_rera_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='button_color',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='rera_color',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
