# Generated by Django 5.2.7 on 2025-12-12 17:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_button_color_setting_rera_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cookies',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='disclaimer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='privacy_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='terms_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
