# Generated by Django 5.2.7 on 2025-12-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_setting_cookies_setting_disclaimer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
