# Generated by Django 5.2.7 on 2025-12-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_impactmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Search & Shortlisting', 'Search & Shortlisting'), ('Book Site Visit', 'Book Site Visit'), ('Home Loan Assistance', 'Home Loan Assistance'), ('Legal Advice', 'Legal Advice'), ('Unit Booking', 'Unit Booking'), ('Get In Touch', 'Get In Touch')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
