# Generated by Django 5.2.7 on 2025-12-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontact',
            name='type',
            field=models.CharField(choices=[('Book Site Visit', 'Book Site Visit'), ('Unit Booking', 'Unit Booking'), ('Home Loan Assistance', 'Home Loan Assistance'), ('Legal Advice', 'Legal Advice'), ('Get In Touch', 'Get In Touch')], max_length=50),
        ),
    ]
