# Generated by Django 5.2.7 on 2025-12-31 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homecontact_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeContact',
        ),
    ]
