# Generated by Django 5.2.7 on 2026-01-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_homecontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='favicon',
            new_name='offer_img',
        ),
    ]
