# Generated by Django 5.2.7 on 2026-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_setting_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='googletagmanager',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
