# Generated by Django 5.2.7 on 2026-07-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_enquiry_email_alter_enquiry_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order'], 'verbose_name_plural': 'Slider Section'},
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='slider',
            name='badge_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='descriptions',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='hero/'),
        ),
    ]
