# Generated by Django 5.2.7 on 2026-07-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_slider_options_rename_title_slider_title1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'About Section'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='awards_recognitions',
        ),
        migrations.RemoveField(
            model_name='about',
            name='happy_families',
        ),
        migrations.RemoveField(
            model_name='about',
            name='highlight_icon_color',
        ),
        migrations.RemoveField(
            model_name='about',
            name='home_bg',
        ),
        migrations.RemoveField(
            model_name='about',
            name='looking_to_button_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='looking_to_button_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='looking_to_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='looking_to_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='about',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='our_mission',
        ),
        migrations.RemoveField(
            model_name='about',
            name='our_mission_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='our_vision',
        ),
        migrations.RemoveField(
            model_name='about',
            name='our_vision_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='projects_delivered',
        ),
        migrations.RemoveField(
            model_name='about',
            name='search_bg',
        ),
        migrations.RemoveField(
            model_name='about',
            name='who_we_are_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='who_we_are_subtitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='who_we_are_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='years_of_excellence',
        ),
    ]
