# Generated by Django 5.2.7 on 2026-07-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_about_about_content_about_about_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='why_choose',
            name='icons',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-solid fa-star')", max_length=20, null=True),
        ),
    ]
