# Generated by Django 5.2.7 on 2026-07-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_why_choose_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='right_image1',
            field=models.ImageField(blank=True, help_text='Main image for About section', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='right_image2',
            field=models.ImageField(blank=True, help_text='Main image for About section', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat1_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='stat2_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
