# Generated by Django 5.2.7 on 2026-07-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_about_right_image1_about_right_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='stat1_title',
            new_name='happy_families',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='stat2_title',
            new_name='years_of_experience',
        ),
    ]
