# Generated by Django 5.2.7 on 2026-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_stat1_title_about_happy_families_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='unique_selling_proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'USP',
            },
        ),
    ]
