# Generated by Django 5.2.7 on 2026-07-06 03:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_unique_selling_proposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='button_one_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='button_one_text',
            field=models.CharField(blank=True, default='Explore Legacy', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='button_two_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='button_two_text',
            field=models.CharField(blank=True, default='View Projects', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Hero Background Image', null=True, upload_to='about/hero/'),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Hero description', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_highlight',
            field=models.CharField(blank=True, help_text='Highlighted text in Hero Title', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Small heading above Hero Title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Main Hero Heading', max_length=250, null=True),
        ),
    ]
