# Generated by Django 5.2.7 on 2026-07-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_about_button_one_link_about_button_one_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='current_project_rera',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
