# Generated by Django 5.2.7 on 2026-07-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_setting_current_project_rera'),
    ]

    operations = [
        migrations.CreateModel(
            name='USP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-solid fa-circle-check', help_text='Example: fa-solid fa-circle-check', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'USP',
                'verbose_name_plural': 'USP Section',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='unique_selling_proposition',
        ),
    ]
