# Generated by Django 5.2.7 on 2026-07-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_usp_delete_unique_selling_proposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
