# Generated by Django 5.2.7 on 2026-07-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_setting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='working_days',
            field=models.CharField(blank=True, help_text='Example: Mon - Sun', max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Example: 10:00 AM - 6:00 PM', max_length=100),
        ),
    ]
