# Generated by Django 5.2.7 on 2026-07-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_setting_working_days_setting_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Schedule Visit',
                'verbose_name_plural': 'Schedule Visits',
                'ordering': ['-created_at'],
            },
        ),
    ]
