# Generated by Django 5.2.7 on 2025-12-08 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.property'),
        ),
    ]
