# Generated by Django 5.2.7 on 2025-12-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='featured_locality',
            field=models.BooleanField(default=False),
        ),
    ]
